spring:
  application:
    name: smartecbot-posts
  datasource:
    url: jdbc:postgresql://${host_db:localhost}:${port_db:5432}/${db_name:smartec_posting_bot}
    username: ${db_user:postgres}
    password: ${db_password:postgres}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail_user_name:userName}
    password: ${mail_user_password:userPassword}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: ${db_ddl_auto:none}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: ${db_schema:smartec_posting_bot}
        temp:
          use_jdbc_metadata: false
        ddl-auto: ${db_ddl_auto:none}
        globally_quoted_identifiers: false
    show-sql: false
  sql:
    init:
      platform: postgresql

server:
  port: ${server_port:8080}
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    root: ${logging_level:INFO}
com:
  smartecmx:
    postingbot:
      util:
        imgflip:
          imgflip_url: ${imgflipUrl:https://api.imgflip.com/caption_image}
          imgflip_username: ${imgflipUsername:imflipUsername}
          imgflip_password: ${imgflipPassword:imgflipPassword}
        facebook:
          api_version: ${facebookApiVersion:v23.0}
          app_id: ${facebookAppId:facebookAppId}
          app_secret: ${facebookAppSecret:facebookAppSecret}
          page_id: ${facebookPageId:page_id}
          get_personal_long_life_token_url: ${getPersonalLongLifeTokenUrl:https://graph.facebook.com/${com.smartecmx.postingbot.util.facebook.api_version}/oauth/access_token}
          get_page_long_life_token_url: ${getPageLongLifeTokenUrl:https://graph.facebook.com/${com.smartecmx.postingbot.util.facebook.api_version}/me/accounts}
          facebook_post_url: ${facebookPostUrl:https://graph.facebook.com/${com.smartecmx.postingbot.util.facebook.api_version}/${com.smartecmx.postingbot.util.facebook.page_id}/photos}
          debug_token_url: ${debugTokenUrl:https://graph.facebook.com/debug_token}
        instagram:
          business_account_id: ${instagramBusinessAccountId:instagramBusinessAccountId}
          create_container_url: ${instagramCreateContainerUrl:https://graph.facebook.com/${com.smartecmx.postingbot.util.facebook.api_version}/${com.smartecmx.postingbot.util.instagram.business_account_id}/media}
          publish_container_url: ${instagramPublishContainerUrl:https://graph.facebook.com/${com.smartecmx.postingbot.util.facebook.api_version}/${com.smartecmx.postingbot.util.instagram.business_account_id}/media_publish}
        mail:
          notifications_receiver: ${notificationsReceiver:notificationsReceiver}
          notifications_receiver_cc: ${notificationsReceiverCc:notificationsReceiverCc}
